/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorLock_Indication_Type.h
 * Generated on: Tue Jan 23 24:58:33 EET
 ********************************************************************/

#ifndef RTE_SWC_DOORLOCK_INDICATION_TYPE_H
#define RTE_SWC_DOORLOCK_INDICATION_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define My_uint8_LowerLimit  (0U)
#define My_uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_DOORLOCK_INDICATION_TYPE_H */
