/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorSensor_LedActuator_Abs.h
 * Generated on: Tue Jan 23 24:58:33 EET
 ********************************************************************/

#ifndef RTE_SWC_DOORSENSOR_LEDACTUATOR_ABS_H
#define RTE_SWC_DOORSENSOR_LEDACTUATOR_ABS_H

#include "Rte_SWC_DoorSensor_LedActuator_Abs_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC_DoorSensor_LedActuator_Abs * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC_DoorSensor_LedActuator_Abs * const Rte_Inst_SWC_DoorSensor_LedActuator_Abs;

/************************ application errors *************************/

#define RTE_E_CS_LedSwitch_E_OK ((Std_ReturnType)0)
#define RTE_E_CS_LedSwitch_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_SR_DoorLock
 * Interface:	SR_DoorLock
 * DataElement:	DoorState
 * Runnable:	Read_DoorSensor
 *****************************************************/
extern void Rte_IWrite_SWC_DoorSensor_LedActuator_Abs_Read_DoorSensor_PP_SR_DoorLock_DoorState (My_uint8 DoorState);
#ifndef IN_RTE_C
#define Rte_IWrite_Read_DoorSensor_PP_SR_DoorLock_DoorState(RTEData) \
	Rte_IWrite_SWC_DoorSensor_LedActuator_Abs_Read_DoorSensor_PP_SR_DoorLock_DoorState(RTEData)
#endif
extern My_uint8* Rte_IWriteRef_SWC_DoorSensor_LedActuator_Abs_Read_DoorSensor_PP_SR_DoorLock_DoorState(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Read_DoorSensor_PP_SR_DoorLock_DoorState() \
	Rte_IWriteRef_SWC_DoorSensor_LedActuator_Abs_Read_DoorSensor_PP_SR_DoorLock_DoorState()
#endif

/*****************************************************
 * Port: 		PP_CS_LedSwitch
 * Interface:	CS_LedSwitch
 * Operation:	LedSwitch
 *****************************************************/
extern Std_ReturnType Set_LedSwitch_Runnable(My_uint8 LedState) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Read_DoorSensor
 * Period:		0.01
 *****************************************************/
extern void Read_DoorSensor_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_DOORSENSOR_LEDACTUATOR_ABS_H */
