/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorLock_Indication_.c
 * Generated on: Tue Jan 23 24:58:33 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SWC_DoorLock_Indication.h"

extern Std_ReturnType Set_LedSwitch_Runnable(My_uint8 LedState);

Rte_DE_My_uint8 Read_DoorSensor_PP_SR_DoorLock_DoorState;
Rte_DE_My_uint8 DoorLock_Indication_Algo_RP_SR_DoorLock_DoorState;


const Rte_CDS_SWC_DoorLock_Indication Rte_Instance_SWC_DoorLock_Indication = {
&Read_DoorSensor_PP_SR_DoorLock_DoorState
};

const Rte_CDS_SWC_DoorLock_Indication * const Rte_Inst_SWC_DoorLock_Indication = &Rte_Instance_SWC_DoorLock_Indication;


Std_ReturnType SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch_Buffer_retcode = RTE_E_OK;

FunctionPtr_SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch Rte_Call_SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch_Delegate = 0;

My_uint8 Rte_IRead_SWC_DoorLock_Indication_DoorLock_Indication_Algo_RP_SR_DoorLock_DoorState (void)
{
	return (Rte_Inst_SWC_DoorLock_Indication)->DoorLock_Indication_Algo_RP_SR_DoorLock_DoorState->value;
}
Std_ReturnType Rte_Call_SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch (My_uint8 LedState)
{
	Std_ReturnType __result = SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch_Buffer_retcode;
	if ( Rte_Call_SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch_Delegate != 0 ) {
		__result = Rte_Call_SWC_DoorLock_Indication_RP_CS_LedSwitch_LedSwitch_Delegate(LedState);
	}

	// Synchronous Call -> LedSwitch(Runnable)
	Set_LedSwitch_Runnable(LedState);
	return __result;
}
