/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorSensor_LedActuator_Abs_.c
 * Generated on: Tue Jan 23 24:58:33 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SWC_DoorSensor_LedActuator_Abs.h"


extern Rte_DE_My_uint8 Read_DoorSensor_PP_SR_DoorLock_DoorState;


const Rte_CDS_SWC_DoorSensor_LedActuator_Abs Rte_Instance_SWC_DoorSensor_LedActuator_Abs = {
&Read_DoorSensor_PP_SR_DoorLock_DoorState
};

const Rte_CDS_SWC_DoorSensor_LedActuator_Abs * const Rte_Inst_SWC_DoorSensor_LedActuator_Abs = &Rte_Instance_SWC_DoorSensor_LedActuator_Abs;




void Rte_IWrite_SWC_DoorSensor_LedActuator_Abs_Read_DoorSensor_PP_SR_DoorLock_DoorState (My_uint8 DoorState)
{
	(Rte_Inst_SWC_DoorSensor_LedActuator_Abs)->Read_DoorSensor_PP_SR_DoorLock_DoorState->value = DoorState;
}
My_uint8* Rte_IWriteRef_SWC_DoorSensor_LedActuator_Abs_Read_DoorSensor_PP_SR_DoorLock_DoorState(void)
{
	return &(Rte_Inst_SWC_DoorSensor_LedActuator_Abs)->Read_DoorSensor_PP_SR_DoorLock_DoorState->value;
}
